//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalaveraWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EntregaPellas
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha de solicitud")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaMovimiento { get; set; }
        public string Responsable { get; set; }
        public string TipoMovimiento { get; set; }

        [Display(Name = "Catidad de pellas entregadas")]
        public Nullable<int> CantidadPellas { get; set; }

        [Display(Name = "Numero de carga")]
        public string NumCarga { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
        public Nullable<int> Locacion { get; set; }

        [Display(Name = "Observación")]
        [StringLength(250, ErrorMessage = "La longitud máxima para {0} es de {1}")]
        public string Observacion { get; set; }
    }
}
