//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalaveraWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparacionBarro
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaPreparacion { get; set; }
        public string NumPreparado { get; set; }
        public Nullable<int> BarroNegro { get; set; }
        public Nullable<int> BarroBlanco { get; set; }
        public Nullable<int> Recuperado { get; set; }
        public string EnPiedra { get; set; }
        public string TiempoAgitacion { get; set; }
        public Nullable<int> NumTambos { get; set; }
        public string DesperdicioMojado { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }
    }
}
