//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalaveraWeb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PreparacionBarro
    {
        public int Id { get; set; }

        [DataType(DataType.Date)]
        [Display(Name = "Fecha preparación")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaPreparacion { get; set; }

        [Display(Name = "Número de preparado")]
        public string NumPreparado { get; set; }

        [Display(Name = "Barro negro")]
        public Nullable<int> BarroNegro { get; set; }

        [Display(Name = "Barro blanco")]
        public Nullable<int> BarroBlanco { get; set; }
        public Nullable<int> Recuperado { get; set; }

        [Display(Name = "En piedra")]
        public string EnPiedra { get; set; }

        [Display(Name = "Tiempo de agitación")]
        public string TiempoAgitacion { get; set; }

        [Display(Name = "Número de tambos")]
        public Nullable<int> NumTambos { get; set; }

        [Display(Name = "Desperdicio mojado")]
        public string DesperdicioMojado { get; set; }
        public string Comentario { get; set; }
        public string Estado { get; set; }

        [Display(Name = "Locación")]
        public Nullable<int> Locacion { get; set; }
        public string Editor { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
    }
}
