//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalaveraWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recuperados
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> FechaRecuperado { get; set; }
        public string Responsable { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string NumRecuperado { get; set; }
        public string TipoMovimiento { get; set; }
    }
}
